# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Vijay Sharma
tagline:          'A Mobile Developer'
description:      'First solve the problem. Then write the code.'
url:              http://vijaysharm.github.io/
baseurl:          /

author:
  name:           'Vijay Sharma'
  url:            https://twitter.com/v_sharm

paginate:         5

# Custom vars

github:
  repo:           https://github.com/vijaysharm

disqus.short_name: vijaysharma